config:
  credentials:
  - id: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
      repo: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.azure_independent_griffin.sh
        container: qc.acc_marina_thoughtful_bear
  QC.Doc:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuchsia_logical_lemur.sh
        container: qc.doc_gunmetal_perky_camel
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_confused_opossum.sh
        container: qc.doc_espresso_eager_flamingo
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.purple_generous_horse.sh
        container: qc.doc_polar_alert_toucan
  QC.Lic:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_industrious_swan.sh
        container: qc.lic_cardamom_peppy_roadrunner
  QC.Sec:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cadet_kind_moose.sh
        container: qc.sec_smoke_calm_wildcat
  QC.Sty:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silver_clever_orangutan.sh
        container: qc.sty_periwinkle_resourceful_lobster
  QC.Uni:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fern_brilliant_wasp.sh
        container: qc.uni_gunmetal_curious_camel
  QC.Ver:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ebony_zealous_swan.sh
        container: qc.ver_isabelline_adaptable_dormouse
timeout: 5400
