config:
  credentials:
  - id: https://gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate
      repo: https://gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.clementine_nurturing_komodo.sh
        container: qc.acc_indigo_loving_wombat
  QC.Doc:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_clever_meerkat.sh
        container: qc.doc_flax_wise_meerkat
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_trustworthy_clownfish.sh
        container: qc.doc_ceru_patient_rabbit
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_gracious_gazelle.sh
        container: qc.doc_lagoon_energetic_cobra
  QC.Lic:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_blissful_cheetah.sh
        container: qc.lic_coffee_pensive_dolphin
  QC.Sec:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate bandit:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_productive_bear.sh
        container: qc.sec_zinnia_balanced_narwhal
  QC.Sty:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sand_spontaneous_orangutan.sh
        container: qc.sty_cardamom_polite_quoll
  QC.Uni:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate pytest:
        commands:
        - /usr/bin/env sh .sqa/script.bronze_compassionate_hawk.sh
        container: qc.uni_flax_dizzy_gibbon
  QC.Ver:
    repos:
      gitlab.acnca.pt/eosc/sqaaas/testsqaaasgitciprivate get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sepia_passionate_jaguar.sh
        container: qc.ver_forest_motivated_kraken
timeout: 5400
