config:
  credentials:
  - id: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
    password_var: GIT_PASSWORD
    username_var: GIT_USER
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate:
      branch: main
      credential_tmp: true
      credentials_id: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
      repo: https://gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.turquoise_amused_ibis.sh
        container: qc.acc_mauve_diplomatic_uakari
  QC.Doc:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_wise_gerbil.sh
        container: qc.doc_papaya_restless_kingfisher
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate git:
        commands:
        - /usr/bin/env sh .sqa/script.red_candid_antelope.sh
        container: qc.doc_iris_diplomatic_caribou
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tangerine_quirky_phoenix.sh
        container: qc.doc_pine_tough_porpoise
  QC.Lic:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate licensee:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_sarcastic_penguin.sh
        container: qc.lic_amethyst_restless_flounder
  QC.Sec:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fern_careful_chimpanzee.sh
        container: qc.sec_onyx_driven_llama
  QC.Sty:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate flake8:
        commands:
        - /usr/bin/env sh .sqa/script.iris_clever_serval.sh
        container: qc.sty_pearl_warm_grizzly
  QC.Uni:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate pytest:
        commands:
        - /usr/bin/env sh .sqa/script.red_unique_dhole.sh
        container: qc.uni_sunset_assured_opossum
  QC.Ver:
    repos:
      gitlab.a.incd.pt/eosc/sqaaas/testsqaaasgitciprivate get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.alabaster_lucky_hummingbird.sh
        container: qc.ver_aqua_sociable_starfish
timeout: 5400
