services:
  qc.acc_brown_artistic_okapi:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_gamboge_mature_nymph:
    command: sleep 6000000
    image: bitnami/git:2.34.1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_heather_vigilant_pangolin:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc/markdownlint
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.doc_mint_vigilant_armadillo:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Doc
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.lic_thunder_elated_manatee:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-licensee:9.17.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sec_violet_generous_wolverine:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Sec/bandit
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.sty_glaucous_creative_gecko:
    command: sleep 6000000
    image: pipelinecomponents/flake8:0.19.0
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_denim_apathetic_kiwi:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-pytest:7.1.3-alpha
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.ver_incarnadine_serene_dormouse:
    build:
      context: ./github.com/EOSC-synergy/sqaaas-tooling/QC.Ver
      dockerfile: Dockerfile
    command: sleep 6000000
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
